### ISSUE TITLE
$console not defined in version 1.7.3

### ISSUE THREAD

**Issue by maxferrario-msf** [OnyxXP/Poor_System_Performance#1]
Before `$console.backgroundcolor = "Black"` you have to initialize $console (for me this did the trick: `$console = $host.UI.RawUI`) otherwise you get this error
```
The property 'backgroundcolor' cannot be found on this object. Verify that the property exists and can be set.
At D:\users\m.ferrario\documents\WindowsPowerShell\PSP.1.7.3.ps1:74 char:1
+ $console.backgroundcolor = "Black"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

```

**Comment by OnyxXP** [comment]
Crap! I must have missed a line when I rebuilt it recently. Thank you!!! I'll make the change, test it, and then update git and this.

**Comment by OnyxXP** [comment]
This has been resolved but I'm unsure if it was updated here. I have released a new version and this includes an auto update function as well.
